# Generated by Django 6.0.4 on 2026-04-24 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shorturl',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='shorturl',
            old_name='creaated_at',
            new_name='created_at',
        ),
    ]
